name: mlvalidation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.20.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - scipy>=1.7.0
  - statsmodels>=0.12.0
  - networkx>=2.6.0
  - pip>=21.0.0
  - pip:
    - plotly>=5.3.0
    - prophet>=1.0.0